---
- name: Deploy Kubernetes to Linux hosts
  hosts: k8s_nodes
  vars_files:
    - vars/all
  tasks:
 
  - name: Update Linux OS
    include_role:
      name: update_os
  tags: 
    - update_os
    - deploy_kubernetes

  - name: Install Linux Packages
    include_role:
      name: install_packages
  tags:
    - install_packages
    - deploy_kubernetes

  - name: Add Kubernetes Repo to Apt Sources
    include_role:
      name: add_k8s_repo
  tags:
    - add_repo
    - deploy_kubernetes

  - name: Install Kubernetes Packages
    include_role: 
      name: install_k8s_packages
  tags:
    - install_k8s
    - deploy_kubernetes
...
