---
- name: Deploy Kubernetes to Linux hosts
  hosts: k8s_nodes
  vars_files: 
    - vars/all
  tasks:

  - name: Install Linux Packages
    include_role:
      name: install_packages
    tags:
      - deploy_kubernetes


  - name: Install Kubernetes
    include_role: 
      name: install_k8s
    tags:
      - add_repo
      - install_k8s
      - deploy_kubernetes


  - name: Init Kubernetes
    include_role:
      name: init_k8s
    tags:
      - init_k8s
      - deploy_kubernetes


  - name: Init Kubernetes Network
    include_role:
      name: init_k8s_networking
    tags:
      - init_k8s_network
      - deploy_kubernetes


  - name: Untaint Master Node
    include_role:
      name: untaint_k8s_master
    tags:
      - untaint_master
      - deploy_kubernetes

...
