---
- name: Add Untaint Script to Ansible Home Directory
  template:
    src: untaint_master.sh.j2
    dest: /home/ansible/untaint_master.sh
    mode: 0777
  tags:
    - untaint_master
    - deploy_kubernetes

- name: Execute Untaint Script
  shell: "/home/ansible/untaint_master.sh"
  tags:
    - untaint_master
    - deploy_kubernetes
...
