---
- name: Update Debian distros
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - install_k8s
    - deploy_kubernetes

- name: Install Kubetnetes Packages
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
  tags:
    - install_k8s
    - deploy_kubernetes
