---
- name: Add Kubernetes repo gpg key to server
  template:
    src: k8_key_add.sh.j2
    dest: $HOME/k8_key_add.sh
    mode: 0777
  tags:
    - add_repo
    - deploy_kubernetes

- name: Execute shell script to add key
  shell: "$HOME/k8_key_add.sh"
  tags:
    - add_repo
    - deploy_kubernetes

- name: Add repo list to apt sources
  template:
    src: k8_sources_list.sh.j2
    dest: $HOME/k8_sources_list.sh
    mode: 0777
  tags:
    - add_repo
    - deploy_kubernetes

- name: Execute shell script to add repo
  shell: "$HOME/k8_sources_list.sh"
  tags:
    - add_repo 
    - deploy_kubernetes
