---
- name: Add Kubernetes Init Script to Ansible Home Directory
  template:
    src: init_kubernetes.sh.j2
    dest: /home/ansible/init_kubernetes.sh
    mode: 0776
  tags:
    - init_k8s
    - deploy_kubernetes

- name: Execute Kubernetes Init Script
  shell: "/home/ansible/init_kubernetes.sh"
  tags:
    - init_k8s
    - deploy_kubernetes

- name: Copy Kubernetes Config Script to Ansible Home Directory
  template:
    src: copy_k8s_config.sh.j2
    dest: /home/ansible/copy_k8s_config.sh
    mode: 0776
  tags:
    - init_k8s
    - deploy_kubernetes

- name: Execute Kubernetes Config Script
  shell: "/home/ansible/copy_k8s_config.sh"
  tags:
    - init_k8s
    - deploy_kubernetes
...
