# Run command: $ kubectl create -f apache2_deployer.yaml
# Then run command: $ kubectl get services to see exposed port # of http service

apiVersion: v1
kind: Namespace
metadata:
  name: apache2
  labels:
    name: apache2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
  namespace: apache2
  labels:
    app: apache2
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 3 # tells deployment to run 1 pods matching the template
  template:   # create pods using pod definition in this template
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: ubuntu/apache2:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache2
  namespace: apache2
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache2
