# Run command: $ kubectl create -f apache2_deployer.yaml
# Then run command: $ kubectl get services to see exposed port # of http service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: ubuntu/apache2:latest # Pulls image from docker.io
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-service
spec:
  type: NodePort  # Exposes container to the outside using an ephemeral port #
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache2
