---
- name: Add Kubernetes repo gpg key to server
  template:
    src: k8_key_add.sh.j2
    dest: /home/ansible/k8_key_add.sh
    mode: 0777
  tags:
    - add_repo
    - install_k8s
    - deploy_kubernetes

- name: Execute shell script to add key
  shell: "/home/ansible/k8_key_add.sh"
  tags:
    - add_repo
    - install_k8s
    - deploy_kubernetes

- name: Add repo list to apt sources
  template:
    src: k8_sources_list.sh.j2
    dest: /home/ansible/k8_sources_list.sh
    mode: 0777
  tags:
    - add_repo
    - install_k8s
    - deploy_kubernetes

- name: Execute shell script to add repo
  shell: "/home/ansible/k8_sources_list.sh"
  tags:
    - add_repo
    - install_k8s 
    - deploy_kubernetes


- name: Update Debian distros
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - install_k8s
    - deploy_kubernetes

- name: Install Kubetnetes Packages
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
  tags:
    - install_k8s
    - deploy_kubernetes
...
