---
- name: Install Intial Package Set
  apt:
    pkg:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - git
      - wget
      - mlocate
  
  when: ansible_os_family == "Debian"
  tags:
    - install_packages
    - deploy_kubernetes
